version: '3.9'

services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: ./app
    depends_on:
      - ollama
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./app/imagens:/app/imagens
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true

volumes:
  ollama_data:
