version: '3.9'

services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  app:
    build: ./app
    depends_on:
      - ollama
    volumes:
      - ./app/imagens:/app/imagens
      - ./app/dataset-images:/app/dataset-images/test
      - ./app/resultados.txt:/app/resultados.txt
    stdin_open: true
    tty: true

volumes:
  ollama_data: